routes/web.php
    CURLOPT_POSTFIELDS => "vendor_id=52571&vendor_auth_code=76a7b9870e96b92ebfb9796e3699342788aa125567b37bcddd",
    CURLOPT_HTTPHEADER => array(
        "content-type: application/x-www-form-urlencoded"
    ),
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
    echo "cURL Error #:" . $err;
    } else {
        $response = json_decode($response);
        foreach($response->response as $key => $value){
            if($key > 0 )
            \App\Http\Models\Subscription::create(
                [
                    'name' => $value->name,
                    'type' => 'Normal',
                    'billing_period' => $value->billing_period,
                    'plan_type' => $value->billing_type,
                    'plan_id' => $value->id,
                    'price' => $value->recurring_price->USD,
                    'tablets_number' => rand(3,20),
                    'features' => null,
                    'order' => $key + 1 ,
                    'order_option' => 0,
                ]
            );
        }
        return \App\Http\Models\Subscription::all();
    // return  [json_decode($response)];
    }
});

Route::get('/curlsend', function(){
    $names =['Basic', 'Growing Business', 'Expanding Chain', 'Basic', 'Growing Business', 'Expanding Chain'];
    $lengths =[1, 1, 1, 12, 12, 12];
    $pricing =[50, 90, 140, 480, 864, 1344];
    $result =[];
    foreach($names as $key => $value){
        $result[] = $response = \Ixudra\Curl\Facades\Curl::to('https://vendors.paddle.com/api/2.0/subscription/plans_create ')
        ->withData( [
            'vendor_id' => '52571',
            'vendor_auth_code' => 'eb01818eaf2a0504e42311ccec39fb3298fdaaa66e5f3ef308',
            'plan_name' => $value,
            'plan_trial_days' => 0,
            'plan_length' => $lengths[$key],
            'plan_type' => 'month',
            'main_currency_code' => 'USD',
            'recurring_price_usd' => $pricing[$key]
        ] )
        ->asJson( true )
        ->post();
    }
    return $result;

});
Route::get('/arrangeMenus', function(){
    $menus = \App\Http\Models\Menu::all();
    foreach ($menus as $key => $menu) {
        \App\Http\Models\Arrangment::create([
            'menu_id' => $menu->parent_id,
            'customer_user' => $menu->customer_id,
            'order' => $key,
            'arrangmentable_type' => 'App\Http\Models\Menu',
            'arrangmentable_id' => $menu->id
        ]);
    }
    $items = \App\Http\Models\Item::all();
    foreach ($items as $key => $item) {
        \App\Http\Models\Arrangment::create([
            'menu_id' => $item->menu_id,
            'customer_user' => $item->menu->customer_id,
            'order' => $key,
            'arrangmentable_type' => 'App\Http\Models\Item',
            'arrangmentable_id' => $item->id
        ]);
    }
    return \App\Http\Models\Arrangment::all();
});

Route::group(['prefix' => 'admin', 'middleware' => 'web', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('login', ['as' => 'login', 'uses' => 'AdminLoginController@login']);
    Route::post('login', 'AdminLoginController@doLogin');


    Route::group(['middleware' => ['auth:admin']], function () {
        Route::resource('customer', 'CustomerController');
        Route::resource('subscription', 'SubscriptionController');
        Route::get('login/customer/{id}', ['as' => 'as.diner.login', 'uses' => 'AdminLoginController@loginAsDiner']);


        /*
         * Ajax Requests
         */
        Route::group(['prefix' => 'ajax'], function () {
            Route::post('validation', 'AjaxController@validation');
            Route::get('cities', 'AjaxController@cities');
            Route::post('active_deactivate', 'AjaxController@activeDeactivate');
        });

        Route::any('logout', 'AdminLoginController@logout');
    });
});

Route::group(['middleware' => 'web', 'namespace' => 'Diner', 'as' => 'diner.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'DinerLoginController@login']);
    Route::post('login', 'DinerLoginController@doLogin');
    Route::group(['prefix' => 'diner', 'middleware' => ['auth:diner']], function () {

        #Route::get('preview/{path}', 'HomeController@index')->where('path','([A-z\d\-\/_.]+)?');
        Route::get('getvenueMenu/{id}','CoustomerUserController@getvenueMenu');
        Route::get('preview','DinerController@preview');
        Route::get('preview/menus','DinerController@preview');
        Route::get('preview/{menuid}/item/{itemid}','DinerController@preview');
        Route::get('preview/sub-menus/{menuids}','DinerController@preview');
        Route::get('menu/{menu_id}/duplicate', 'MenuController@duplicate');

        Route::get('preview/items','DinerController@preview');
        Route::get('preview/login','DinerController@preview');
        Route::get('preview/items/{item_id}','DinerController@preview');

        Route::resource('/', 'DinerController');

        Route::get('/arrange/{id}','ArrangmentController@arrange');

        Route::resource('menu', 'MenuController');
        Route::resource('menu/{parent_id}/sub-menu', 'SubMenuController');
        Route::resource('menu/{menu_id}/item', 'ItemController');
        Route::resource('devices', 'DeviceController');
        Route::get('devices/deleteall/{ids}', 'DeviceController@deleteall');

        Route::resource('order', 'OrderController');

        Route::resource('venue','VenueController');
        Route::get('scan-qr', ['as'=>'scan-qr','uses'=>'VenueController@generateQrCode']);

        Route::get('localization','LocalizationController@index');
        Route::get('/getObjectTranslation/{id}/{type}','LocalizationController@getTranslation');
        Route::get('/updatelanguage','LocalizationController@updatelanguage');
        Route::get('updatesurveylanguage', 'LocalizationController@updatesurveylanguage');
        Route::get('cofigrations', 'ConfigrationController@index')->name('cofigrations.index');
        Route::post('configraton', 'ConfigrationController@store');
        Route::post('venue/import',['as' => 'venue.import','uses'=>'VenueController@import']);
        Route::post('menu/move',['as' => 'menu.move','uses'=>'VenueController@move']);

        Route::resource('campaign', 'CampaignController');
        Route::resource('feedback', 'FeedbackController');
        Route::get('getsurvey/{id}', 'FeedbackController@getsurvey');
        Route::resource('interaction', 'FeedbackInteractionController');
        Route::resource('sidedishes', 'SideDishesController');
        Route::resource('options', 'OptionController');
        Route::resource('tables', 'TableController');
        Route::get('getoption/{id}', 'OptionController@getoption');
        Route::get('sidedishes/destroy/{id}', 'SideDishesController@destroy');
        Route::get('feedback/open-close/{id}', ['as'=>'feedback.open-close','uses'=>'FeedbackController@openClose']);
        Route::get('interaction/open-close/{id}', ['as'=>'interaction.open-close','uses'=>'FeedbackInteractionController@openClose']);
        Route::get('interaction/open-close/{ids}/{status}', ['as'=>'interaction.open-close-all','uses'=>'FeedbackInteractionController@openCloseAll']);

        Route::get('export_survey',['as'=> 'export.survey','uses'=>'FeedbackInteractionController@export']);
        Route::resource('waiters', 'CoustomerUserController');
       
        /*
         * Ajax Requests
        */
        Route::group(['prefix' => 'ajax'], function () {
            Route::post('validation', 'AjaxController@validation');
            Route::get('cities', 'AjaxController@cities');
            Route::post('menu/hide_show', 'AjaxController@HideShowMenu');
            Route::post('item/hide_show', 'AjaxController@HideShowItem');
            Route::post('section/create', 'AjaxController@sectionCreate');
            Route::post('section/remove', 'AjaxController@sectionRemove');
            Route::post('media/upload', 'AjaxController@upload');
            Route::post('edit/customer/plan', ['as' => 'ajax.edit.customer.plan', 'uses' => 'AjaxController@editCustomerPlan']);
        });

        Route::any('logout', 'DinerLoginController@logout');
    });


});

Route::group(['middleware' => 'web', 'namespace' => 'Landing', 'as' => 'landing.'], function () {

    Route::get('verify-first',['as' => 'verify-first', 'uses' => 'LandingController@verifyFirst']);
    Route::get('verify',['as' => 'verify.view', 'uses' => 'LandingController@verify']);

    //Route::get('login', ['as' => 'login', 'uses' => 'DinerLoginController@login']);
    //Route::post('login', 'DinerLoginController@doLogin');

    Route::get('/auth/redirect/{provider}',['as' => 'redirect.facebook','uses' => 'LandingController@redirect'] );
    Route::get('/callback/{provider}', ['as' => 'callback.facebook','uses' => 'LandingController@callback']);

    Route::get('/',['as' => 'index', 'uses' => 'LandingController@index']);
    Route::get('login',['as' => 'login', 'uses' => 'LandingController@login']);
    Route::post('login',['as' => 'submit.login', 'uses' => 'LandingController@submitLogin']);

    Route::get('sign-up',['as' => 'sign-up', 'uses' => 'LandingController@signUp']);
    Route::post('sign-up',['as' => 'submit.signing', 'uses' => 'LandingController@submitSigning']);

    Route::get('features',['as' => 'features', 'uses' => 'LandingController@features']);

    Route::get('blog',['as' => 'blog', 'uses' => 'LandingController@blog']);
    Route::get('blog1',['as' => 'blog1', 'uses' => 'LandingController@blog1']);
    Route::get('blog2',['as' => 'blog2', 'uses' => 'LandingController@blog2']);
    Route::get('blog3',['as' => 'blog3', 'uses' => 'LandingController@blog3']);

    Route::get('pricing',['as' => 'pricing', 'uses' => 'LandingController@pricing']);
    Route::get('terms',['as' => 'terms', 'uses' => 'LandingController@terms']);

app/Http/Controllers/API/SubMenuController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Services\Diner\MenuService;
use Illuminate\Support\Facades\Auth;
Use URL;

class SubMenuController extends APIController
{
    private $menuObj;

    public function __construct(MenuService $menuObj)
    {
        $this->menuObj = $menuObj;
    }


    public function index()
    {
        try {
            $statusCode = 200;
            $this->data['message'] = "data received";
            $this->data['menus'] = [];
            $menus = $this->menuObj->getAll([['parent_id', '=', 0], 'is_active' => 1]);
            if (count($menus)) {
                foreach ($menus as $menu) {
                    $obj = new \stdClass();
                    $obj->id = $menu->id;
                    $obj->name = $menu->name;
                    $obj->display_as = $menu->display_as;
                    $obj->num_of_rows = $menu->num_of_rows;
                    $obj->grid_title_position = $menu->grid_title_position;
                    $obj->display_similar_items = $menu->display_similar_items;
                    $obj->mark_as_new = $menu->mark_as_new;
                    $obj->mark_as_signature = $menu->mark_as_signature;
                    $obj->menu_image = $menu->FullThumbnailImagePath('335X165');
                    $this->data['menus'][] = $obj;
                }
            }

        } catch (\Exception $e) {
            $statusCode = 500;
            $this->data['message'] = $e->getMessage();
        } finally {
            return $this->sendResponse($this->data, $statusCode);
        }

    }

    public function show($id)
    {
        try {
            $menu = $this->menuObj->find(['id' => $id, 'is_active' => 1]);
            $this->data['result'] = $menu;
            if ($menu) {
                $obj = new \stdClass();
                $obj->id = $menu->id;
                $obj->name = $menu->name;
                $obj->display_as = $menu->display_as;
                $obj->num_of_rows = $menu->num_of_rows;
                $obj->grid_title_position = $menu->grid_title_position;
                $obj->display_similar_items = $menu->display_similar_items;
                $obj->mark_as_new = $menu->mark_as_new;
                $obj->mark_as_signature = $menu->mark_as_signature;
                $obj->menu_image = $menu->FullThumbnailImagePath('335X165');
                $obj->sections = [];
                $obj->sub_menus = [];
                $sections_arr = [];

                if (count($menu->sections)) {
                    foreach ($menu->sections as $section) {
                        $section_obj = new \stdClass();
                        $section_obj->id = $section->id;
                        $section_obj->title = $section->title;
                        $subMenu_arr = [];
                        if (count($section->SubMenus)) {
                            foreach ($section->SubMenus as $subMenu) {
                                $subMenu_obj = new \stdClass();
                                $subMenu_obj->id = $subMenu->id;
                                $subMenu_obj->name = $subMenu->name;
                                $subMenu_obj->mark_as_new = $subMenu->mark_as_new;
                                $subMenu_obj->mark_as_signature = $subMenu->mark_as_signature;
                                $subMenu_obj->menu_image = $subMenu->FullThumbnailImagePath('335X165');
                                $subMenu_arr[] = $subMenu_obj;
                            }
                        }
                        $section_obj->sub_menus = $subMenu_arr;
                        $sections_arr[] = $section_obj;
                    }
                    $obj->sections = $sections_arr;
                } elseif (count($menu->SubMenus)) {
                    $subMenu_arr = [];
                    foreach ($menu->SubMenus as $subMenu) {
                        $subMenu_obj = new \stdClass();
                        $subMenu_obj->id = $subMenu->id;
                        $subMenu_obj->name = $subMenu->name;
                        $subMenu_obj->mark_as_new = $subMenu->mark_as_new;
                        $subMenu_obj->mark_as_signature = $subMenu->mark_as_signature;
                        $subMenu_obj->menu_image = $subMenu->FullThumbnailImagePath('335X165');
                        $subMenu_arr[] = $subMenu_obj;
                    }
                    $obj->sub_menus = $subMenu_arr;
                }
                $this->data['result'] = $obj;
                $statusCode = 200;
            } else {
                $statusCode = 404;
            }
            $this->data['message'] = "data received";
        } catch (\Exception $e) {
            $statusCode = 500;
            $this->data['message'] = $e->getMessage();
        } finally {
            return $this->sendResponse($this->data, $statusCode);
        }
    }
}

app/Http/Controllers/Diner/ArrangmentController.php
<?php

namespace App\Http\Controllers\Diner;

use Illuminate\Http\Request;
use App\Http\Services\Diner\ArrangmentService;
use App\Http\Services\Diner\MenuService;


class ArrangmentController extends DinerController
{
    //
    private $arrangmentObj;
    private $menuObj;
    public function __construct(ArrangmentService $arrangmentObj,MenuService $menuObj)
    {
        parent::__construct();
        $this->arrangmentObj = $arrangmentObj;
        $this->menuObj = $menuObj;
    }
    public function arrange(Request $request,$id){
        $menu = $this->menuObj->find(['id' =>$id]);
        parse_str($request->data,$newOrders);
        $newOrders = array_map('intval',$newOrders['card']);
        $ordered = [];
        foreach($newOrders as $key => $value){
            $newObj = $this->arrangmentObj->find(['id' => $value]);
            $newObj->order = $key +1;
            $newObj->save();
        }
        return ['success' => 'Arrangment Done Successfully'];

        
    }

    
}

app/Http/Controllers/Diner/DinerLoginController.php
<?php

namespace App\Http\Controllers\Diner;

use App\Http\Requests\Common\LoginRequest;
use App\Http\Services\Diner\DinerLoginService;
use Illuminate\Support\Facades\Auth;
Use URL;

class DinerLoginController extends DinerController
{
    private $dinerLoginObj;

    public function __construct(DinerLoginService $dinerLoginObj)
    {
        $this->dinerLoginObj = $dinerLoginObj;
    }

    public function login()
    {
        if (!Auth::guard('diner')->user()) {
            $this->data['title'] = (object)['name' => 'Login'];
            return view('diner.auth.login', $this->data);
        }
        return redirect()->route('diner.menu.index');
    }

    public function doLogin(LoginRequest $request)
    {
        $credentials = $request->except(['_token', 'remember']);

        $isLogin = $this->dinerLoginObj->login($credentials, $request->remember);

        if ($isLogin) {
            return redirect()->route('diner.menu.index')->with(['success' => 'Logged in successfully']);
        } else {
            return redirect()->back()->with('fail', 'Whoops something wrong');
        }

    }

    public function logout()
    {
        $this->dinerLoginObj->logout();
        return redirect()->route('landing.login');
    }
}

resources/views/diner/sub-menu/create.blade.php
@extends('diner.layouts.master')

@section('content')


    <div class="container">
        {{Form::open(array('url'=>array('diner/menu/'.$parent_id.'/sub-menu'.'?venue_id='.$venue_id) ,'method'=>'POST','files'=>'true','enctype'=>'multipart/form-data'))}}
            <div class="row row-title">
                
                <div class="col-md-12 text-left">
                    <i class="fas fa-chevron-left"></i>&nbsp; Menus 
                </div>
                <div class="col-md-6 text-left"><h6>Create New SubMenu</h6></div>
                <div class="col-md-6 text-right">
                    {{-- <i class="fa fa-search"></i>  --}}
                    {{-- @if(count($mainMenus) || $user_branch->parent_id != 0)
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"><a href="#">Import Menu</a></button>
                    @endif --}}
                    <button class="btn btn-primary" type="submit">Save Menu</button>
                </div>
            </div>
            <div class="row menus-fBox">
                <div class="col-md-7">
                    <div class="create-inp">
                        <label for="">Menu Name</label>
                        <input type="text" name="name" value="{{old('name')}}" data-validation="required server"
                        data-validation-url="{{URL::to('diner/ajax/validation')}}"
                        data-validation-req-params='{"model":"menu","_token":"{{csrf_token()}}","parent_id":"0"}'
                        id="menu-name" placeholder="Add Menu title" class="form-control">
                    </div>
                    <div class="create-inp">
                        <label for="">Description</label>
                        <textarea name="description" placeholder="Type a menu description" class="form-control"></textarea>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="create-inp">
                                <label for="">Display as</label>
                                <br>
                                <select name="display_as" id="display_as">
                                    <option value="" class="form-control" disabled>select option</option>
                                    <option value="grid" {{old('display_as')=='grid' ? 'selected':''}}>Grid</option>
                                    <option value="list" {{old('display_as')=='list' ? 'selected':''}}>List</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6" id="num_of_rows">
                            <div class="create-inp">
                                <label for="">Number of Colums</label>
                                <br>
                                <select name="num_of_rows" >
                                    <option value="" disabled selected>Number of Columns</option>
                                    <option value="2" {{old('num_of_rows')=='2' ? 'selected':''}}>2</option>
                                    <option value="4" {{old('num_of_rows')=='4' ? 'selected':''}}>4</option>
                                    <option value="6" {{old('num_of_rows')=='6' ? 'selected':''}}>6</option>
                                    <option value="8" {{old('num_of_rows')=='8' ? 'selected':''}}>8</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="create-inp">
                        <label for="">Crid View Title Position</label>
                        <br>
                        <select name="grid_title_position" id="grid_title_position">
                            <option value="" disabled selected>Grid View Title Position</option>
                            <option value="top" {{old('grid_title_position')=='top' ? 'selected':''}}>Top</option>
                            <option value="bottom" {{old('grid_title_position')=='bottom' ? 'selected':''}}>Bottom</option>
                        </select>
                    </div>
                    <br>
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-9 col-10">
                                <h6>Display Similar Items</h6>
                                <div style="margin-top: -10px;">
                                    <small>Display other Items of the Category on each item Page</small>
                                </div>
                            </div>
                            <div class="col-md-3 col-2 text-right">
                                <input type="checkbox" name="display_similar_items"
                                {{old('display_similar_items') == 1? 'checked':''}} value="1" class="checkboxx">
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-5 col-6">
                        <div class="row">
                            <div class="col-md-9 col-11">
                                <h6>Mark Menu as New</h6>
                            </div>
                            <div class="col-md-3 col-1"><input name="mark_as_new" value="1"
                                id="mark_as_new" {{old('mark_as_new') == 1? 'checked':''}} type="checkbox" class="checkboxx"></div>
                        </div>
                    </div>
                    <div class="col-md-7 col-6 text-right">
                        <div class="row">
                            <div class="col-md-8 col-11">
                                <h6>Mark Menus as signature</h6>
                            </div>
                            <div class="col-md-4 col-1"><input name="mark_as_signature" value="1"
                                id="mark_as_signature" {{old('mark_as_signature') == 1? 'checked':''}} type="checkbox" class="checkboxx"></div>
                        </div>
                    </div>
                </div>
                <div class="create-inp">
                        <label for="">Add additional Notes</label>
                        <textarea name="additional_notes" placeholder="Type any Notes" class="form-control"></textarea>
                    </div>
                </div>
                
                <div class="col-md-5">
                    <div class="upload" id="imageDiv" upload-image="" style="box-shadow: 0px 0px 6px 0px rgba(0,0,0,.2); border-radius: 10px;">
                        <input type="file" id="uploadImage" name="file" class="input-file ng-pristine ng-valid ng-touched" files-model="" ng-model="project.fileList">
                        <label for="files" style="border: none">
                            <span class="add-image" style="color: #47e6fc">
                                <i class="far fa-image"></i> Upload Picture
                            </span>
                            <output id="list"></output>
                        </label>
                    </div>
                    <br>
                    <div class="upload" upload-image="" style="background: transparent">
                        <input type="file" id="files" name="video" class="input-file ng-pristine ng-valid ng-touched" files-model="" ng-model="project.fileList">
                        <label for="files" style="border: none">
                            <span class="add-image" style="color: #47e6fc">
                                <i class="far fa-file-video"></i> Add a Video
                            </span>
                            <output id="list"></output>
                        </label>
                    </div>
                </div>
                
            </div>  
            <br><br><br>
        {{ Form::close() }}
        <!--    MODEL  -->
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <br><br><br><br>
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header import-head-modal">
                    <h4><b>Import Menus</b></h4>
                    </div>
                    {{ Form::open(array('url'=>route('diner.venue.import',['venue_id'=>$venue_id]) ,'method'=>'POST','files'=>'true','enctype'=>'multipart/form-data'))}}
                        <div class="modal-body create-menu-import">
                            <div class="create-inp">
                                <label for=""><b>Select a Venue</b></label>
                                <br>
                                <select name="customer_id" id="">
                                    <option value="" class="form-control">Classic's Utah</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                </select>
                            </div>
                            <div class="create-inp">
                                <label for=""><b>Select a Menu</b></label>
                                <br>
                                <select name="menu_id" id="">
                                    <option value="" class="form-control">Utah's Menu</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-dafult" data-dismiss="modal" style="color: #ccc; font-weight: 500; letter-spacing: 1px">Cancel</button>
                            <button type="button" class="btn btn-primary" style="padding: 10px 30px"><a href="importmenu.html">Import</a></button>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>  
    </div>

    
@stop

@section('scripts')


    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#display_as").trigger("change");
        });

        $.validate({modules: 'security'});
        $('#display_as').change(function () {
            val = $(this).val();
            if (val == 'grid') {
                $('#num_of_rows').attr('data-validation', 'required');
                $('#grid_title_position').attr('data-validation', 'required');
                $('#num_of_rows').removeClass('d-none');
                $('#grid_title_position').removeClass('d-none');
            } else {
                $('#num_of_rows').val('');
                $('#grid_title_position').val('');
                $('#num_of_rows').addClass('d-none');
                $('#grid_title_position').addClass('d-none');
                $('#num_of_rows').removeAttr('data-validation');
                $('#grid_title_position').removeAttr('data-validation');
            }
        })

        $("#uploadImage").on("change", function(){
            // Get a reference to the fileList
            var files = !!this.files ? this.files : [];
            // If no files were selected, or no FileReader support, return
            if ( !files.length || !window.FileReader ) return;
            // Only proceed if the selected file is an image
            if ( /^image/.test( files[0].type ) ) {
                // Create a new instance of the FileReader
                var reader = new FileReader();
                // Read the local file as a DataURL
                reader.readAsDataURL( files[0] );

                // When loaded, set image data as background of page
                reader.onloadend = function(){
                    $("#imageDiv").css("background-image", 'url(' + this.result + ')');
                }
            }
        });

    </script>


@stop

resources/views/diner/sub-menu/index.blade.php
@extends('diner.layouts.master')

@section('content')

    <div class="row">
        @if($menus)
            @foreach($menus as $menu)
                <div class="col-md-4 col-12">
                    <div class="cat-block">
                        <div class="cat-block-inner">
                            <img src="{{$menu->FullThumbnailImagePath('500X500')}}">
                        </div>

                        <div class="cat-block-title">
                            <h4>{{$menu->name}}</h4>
                            <a class="text-muted" href="{{ URL::to('diner/menu/' . $menu->id . '/edit')}}">
                                <i class="fas fa-pencil-alt"></i></a>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif
    </div>
@stop