routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
view()->share('vuePath',url('').'/../resources/js/');
view()->share('resource',url('').'/');


Route::get('getplans', function () {
    $curl = curl_init();

    curl_setopt_array($curl, array(
    CURLOPT_URL => "https://vendors.paddle.com/api/2.0/subscription/plans",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => "vendor_id=52571&vendor_auth_code=76a7b9870e96b92ebfb9796e3699342788aa125567b37bcddd",
    CURLOPT_HTTPHEADER => array(
        "content-type: application/x-www-form-urlencoded"
    ),
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
    echo "cURL Error #:" . $err;
    } else {
        $response = json_decode($response);
        foreach($response->response as $key => $value){
            if($key > 0 )
            \App\Http\Models\Subscription::create(
                [
                    'name' => $value->name,
                    'type' => 'Normal',
                    'billing_period' => $value->billing_period,
                    'plan_type' => $value->billing_type,
                    'plan_id' => $value->id,
                    'price' => $value->recurring_price->USD,
                    'tablets_number' => rand(3,20),
                    'features' => null,
                    'order' => $key + 1 ,
                    'order_option' => 0,
                ]
            );
        }
        return \App\Http\Models\Subscription::all();
    // return  [json_decode($response)];
    }
});

Route::get('/curlsend', function(){
    $names =['Basic', 'Growing Business', 'Expanding Chain', 'Basic', 'Growing Business', 'Expanding Chain'];
    $lengths =[1, 1, 1, 12, 12, 12];
    $pricing =[50, 90, 140, 480, 864, 1344];
    $result =[];
    foreach($names as $key => $value){
        $result[] = $response = \Ixudra\Curl\Facades\Curl::to('https://vendors.paddle.com/api/2.0/subscription/plans_create ')
        ->withData( [
            'vendor_id' => '52571',
            'vendor_auth_code' => 'eb01818eaf2a0504e42311ccec39fb3298fdaaa66e5f3ef308',
            'plan_name' => $value,
            'plan_trial_days' => 0,
            'plan_length' => $lengths[$key],
            'plan_type' => 'month',
            'main_currency_code' => 'USD',
            'recurring_price_usd' => $pricing[$key]
        ] )
        ->asJson( true )
        ->post();
    }
    return $result;

});
Route::get('/arrangeMenus', function(){
    $menus = \App\Http\Models\Menu::all();
    foreach ($menus as $key => $menu) {
        \App\Http\Models\Arrangment::create([
            'menu_id' => $menu->parent_id,
            'customer_user' => $menu->customer_id,
            'order' => $key,
            'arrangmentable_type' => 'App\Http\Models\Menu',
            'arrangmentable_id' => $menu->id
        ]);
    }
    $items = \App\Http\Models\Item::all();
    foreach ($items as $key => $item) {
        \App\Http\Models\Arrangment::create([
            'menu_id' => $item->menu_id,
            'customer_user' => $item->menu->customer_id,
            'order' => $key,
            'arrangmentable_type' => 'App\Http\Models\Item',
            'arrangmentable_id' => $item->id
        ]);
    }
    return \App\Http\Models\Arrangment::all();
});

Route::group(['prefix' => 'admin', 'middleware' => 'web', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('login', ['as' => 'login', 'uses' => 'AdminLoginController@login']);
    Route::post('login', 'AdminLoginController@doLogin');


    Route::group(['middleware' => ['auth:admin']], function () {
        Route::resource('customer', 'CustomerController');
        Route::resource('subscription', 'SubscriptionController');
        Route::get('login/customer/{id}', ['as' => 'as.diner.login', 'uses' => 'AdminLoginController@loginAsDiner']);


        /*
         * Ajax Requests
         */
        Route::group(['prefix' => 'ajax'], function () {
            Route::post('validation', 'AjaxController@validation');
            Route::get('cities', 'AjaxController@cities');
            Route::post('active_deactivate', 'AjaxController@activeDeactivate');
        });

        Route::any('logout', 'AdminLoginController@logout');
    });
});

Route::group(['middleware' => 'web', 'namespace' => 'Diner', 'as' => 'diner.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'DinerLoginController@login']);
    Route::post('login', 'DinerLoginController@doLogin');
    Route::group(['prefix' => 'diner', 'middleware' => ['auth:diner']], function () {

        #Route::get('preview/{path}', 'HomeController@index')->where('path','([A-z\d\-\/_.]+)?');
        Route::get('getvenueMenu/{id}','CoustomerUserController@getvenueMenu');
        Route::get('preview','DinerController@preview');
        Route::get('preview/menus','DinerController@preview');
        Route::get('preview/{menuid}/item/{itemid}','DinerController@preview');
        Route::get('preview/sub-menus/{menuids}','DinerController@preview');
        Route::get('menu/{menu_id}/duplicate', 'MenuController@duplicate');

        Route::get('preview/items','DinerController@preview');
        Route::get('preview/login','DinerController@preview');
        Route::get('preview/items/{item_id}','DinerController@preview');

        Route::resource('/', 'DinerController');

        Route::get('/arrange/{id}','ArrangmentController@arrange');

        Route::resource('menu', 'MenuController');
        Route::resource('menu/{parent_id}/sub-menu', 'SubMenuController');
        Route::resource('menu/{menu_id}/item', 'ItemController');
        Route::resource('devices', 'DeviceController');
        Route::get('devices/deleteall/{ids}', 'DeviceController@deleteall');

        Route::resource('order', 'OrderController');

        Route::resource('venue','VenueController');
        Route::get('scan-qr', ['as'=>'scan-qr','uses'=>'VenueController@generateQrCode']);

        Route::get('localization','LocalizationController@index');
        Route::get('/getObjectTranslation/{id}/{type}','LocalizationController@getTranslation');
        Route::get('/updatelanguage','LocalizationController@updatelanguage');
        Route::get('updatesurveylanguage', 'LocalizationController@updatesurveylanguage');
        Route::get('cofigrations', 'ConfigrationController@index')->name('cofigrations.index');
        Route::post('configraton', 'ConfigrationController@store');
        Route::post('venue/import',['as' => 'venue.import','uses'=>'VenueController@import']);
        Route::post('menu/move',['as' => 'menu.move','uses'=>'VenueController@move']);

        Route::resource('campaign', 'CampaignController');
        Route::resource('feedback', 'FeedbackController');
        Route::get('getsurvey/{id}', 'FeedbackController@getsurvey');
        Route::resource('interaction', 'FeedbackInteractionController');
        Route::resource('sidedishes', 'SideDishesController');
        Route::resource('options', 'OptionController');
        Route::resource('tables', 'TableController');
        Route::get('getoption/{id}', 'OptionController@getoption');
        Route::get('sidedishes/destroy/{id}', 'SideDishesController@destroy');
        Route::get('feedback/open-close/{id}', ['as'=>'feedback.open-close','uses'=>'FeedbackController@openClose']);
        Route::get('interaction/open-close/{id}', ['as'=>'interaction.open-close','uses'=>'FeedbackInteractionController@openClose']);
        Route::get('interaction/open-close/{ids}/{status}', ['as'=>'interaction.open-close-all','uses'=>'FeedbackInteractionController@openCloseAll']);

        Route::get('export_survey',['as'=> 'export.survey','uses'=>'FeedbackInteractionController@export']);
        Route::resource('waiters', 'CoustomerUserController');
       
        /*
         * Ajax Requests
        */
        Route::group(['prefix' => 'ajax'], function () {
            Route::post('validation', 'AjaxController@validation');
            Route::get('cities', 'AjaxController@cities');
            Route::post('menu/hide_show', 'AjaxController@HideShowMenu');
            Route::post('item/hide_show', 'AjaxController@HideShowItem');
            Route::post('section/create', 'AjaxController@sectionCreate');
            Route::post('section/remove', 'AjaxController@sectionRemove');
            Route::post('media/upload', 'AjaxController@upload');
            Route::post('edit/customer/plan', ['as' => 'ajax.edit.customer.plan', 'uses' => 'AjaxController@editCustomerPlan']);
        });

        Route::any('logout', 'DinerLoginController@logout');
    });


});

Route::group(['middleware' => 'web', 'namespace' => 'Landing', 'as' => 'landing.'], function () {

    Route::get('verify-first',['as' => 'verify-first', 'uses' => 'LandingController@verifyFirst']);
    Route::get('verify',['as' => 'verify.view', 'uses' => 'LandingController@verify']);

    //Route::get('login', ['as' => 'login', 'uses' => 'DinerLoginController@login']);
    //Route::post('login', 'DinerLoginController@doLogin');

    Route::get('/auth/redirect/{provider}',['as' => 'redirect.facebook','uses' => 'LandingController@redirect'] );
    Route::get('/callback/{provider}', ['as' => 'callback.facebook','uses' => 'LandingController@callback']);

    Route::get('/',['as' => 'index', 'uses' => 'LandingController@index']);
    Route::get('login',['as' => 'login', 'uses' => 'LandingController@login']);

app/Http/Controllers/API/OrderController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Services\Diner\ItemService;
use App\Http\Services\Diner\OrderService;
use App\Http\Services\Diner\CartService;
use App\Http\Services\Diner\CartItemService;
use App\Http\Services\Diner\CartItemOptionService;
use App\Http\Services\Diner\CartItemSideDishService;

use App\Http\Services\Common\Helper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
Use URL;

class OrderController extends Controller
{
    private $itemObj;
    private $itemOptionObj;
    private $orderObj;
    private $itemSideDishObj;
    private $itemPriceObj;
    private $cartObj;
    private $cartItemObj;
    private $cartItemOptionObj;
    private $cartItemSideDishObj;
    private $helperObj;

    public function __construct(
        ItemService $itemObj,
        OrderService $orderObj,
        CartService $cartObj,
        CartItemService $cartItemObj,
        CartItemOptionService $cartItemOptionObj,
        CartItemSideDishService $cartItemSideDishObj,
        Helper $helperObj
    )
    {
        $this->middleware(function ($request, $next) {
            $this->user = Auth::guard('api')->user();
            $this->customer = Auth::guard('venue')->user();
            $this->customerId = $this->customer ? $this->customer->id : $this->user->customer_id;
            return $next($request);
        });
        $this->itemObj = $itemObj;
        $this->orderObj = $orderObj;
        $this->cartObj = $cartObj;
        $this->cartItemObj = $cartItemObj;
        $this->cartItemOptionObj = $cartItemOptionObj;
        $this->cartItemSideDishObj = $cartItemSideDishObj;
        $this->helperObj = $helperObj;
    }

    public function submitOrder(Request $request)
    {
        //$customer = $this->user->Customer;
        //$statusCode = 200;
        //$message = "Done.";
        //
        //$serviceChargePercentag = 12;
        //$tipPercentag = 0;
        //$taxPercentag = 0;
        //
        //$id = $request->cart_id;
        //$conditions = [
        //'id' => $id,
        //'ordered' => 0,
        //'customer_id' => $customer->id
        //];
        //
        //$cart = $this->cartObj->find($conditions,['items']);
        //return $cart;
        try {
            $customer = $this->user->Customer ?? $this->customer;
            $statusCode = 200;
            $message = "Done.";

            $serviceChargePercentag = 0.12;
            $taxPercentag = 0.14;
            $tipPercentag = 0;

            $id = $request->cart_id;
            $conditions = [
                'id' => $id,
                'ordered' => 0,
                'customer_id' => $customer->id
            ];

            $cart = $this->cartObj->find($conditions,['items']);
            if($cart) {
                $serviceCharge = $cart->total_cost * $serviceChargePercentag;
                $tax = $cart->total_cost * $taxPercentag;

                $total = $cart->total_cost + $serviceCharge +$tax;
                $orderData = [
                    'cart_id' => $id,
                    'table_number' => $cart->table_number,
                    'customer_user_id' => $this->user->id ?? null,
                    'customer_id' => $this->customerId,
                    'service_charge' => $serviceCharge,
                    'tax' => $tax,
                    'tip' => $cart->total_cost * $tipPercentag,
                    'total_cost' => $total,
                    'status' => 'close',
                ];
                $this->orderObj->insert($orderData);

                $this->cartObj->update($conditions,['ordered'=>1]);

            } else {
                $statusCode = 404;
                $message = "Cart not found.";
            }
        } catch (\Exception $e) {
            $statusCode = 500;
            $message = $e->getMessage();
        } finally {
            return parent::jsonResponse($statusCode,$message);
        }
    }

    public function openedOrders(Request $request)
    {
        try {
            $statusCode = 200;
            $message = "Done.";
            $conditions = array();
            $conditions['status'] = 'open';
            $conditions['customer_id'] = $this->customerId;
            if($this->user)
                $conditions['customer_user_id'] = $this->user->id;
            $result = $this->orderObj->getAll($conditions);

        } catch (\Exception $e) {
            $statusCode = 500;
            $message = $e->getMessage();
            $result = [];
        } finally {
            return parent::jsonResponse($statusCode,$message,$result);
        }
    }

    public function closeOrder(Request $request,$id)
    {
        try {
            $statusCode = 200;
            $message = "Done.";
            $this->order = $this->orderObj->find([
                'id' => $id,
                'status' => 'open',
                'customer_user_id' => $this->user->id
            ]);
            if(!$this->order)
                throw new \Exception('Not Found');

            $this->orderObj->update([
                'id' => $request->id,
                'status' => 'open',
                'customer_user_id' => $this->user->id
            ],['status' => "close"]);

            $this->order = $this->orderObj->find(['id' => $id]);

        } catch (\Exception $e) {
            $statusCode = 500;
            $message = $e->getMessage();
        } finally {
            return parent::jsonResponse($statusCode,$message,$this->order);
        }
    }

}

app/Http/Controllers/Diner/ArrangmentController.php
<?php

namespace App\Http\Controllers\Diner;

use Illuminate\Http\Request;
use App\Http\Services\Diner\ArrangmentService;
use App\Http\Services\Diner\MenuService;


class ArrangmentController extends DinerController
{
    //
    private $arrangmentObj;
    private $menuObj;
    public function __construct(ArrangmentService $arrangmentObj,MenuService $menuObj)
    {
        parent::__construct();
        $this->arrangmentObj = $arrangmentObj;
        $this->menuObj = $menuObj;
    }
    public function arrange(Request $request,$id){
        $menu = $this->menuObj->find(['id' =>$id]);
        parse_str($request->data,$newOrders);
        $newOrders = array_map('intval',$newOrders['card']);
        $ordered = [];
        foreach($newOrders as $key => $value){
            $newObj = $this->arrangmentObj->find(['id' => $value]);
            $newObj->order = $key +1;
            $newObj->save();
        }
        return ['success' => 'Arrangment Done Successfully'];

        
    }

    
}

app/Http/Controllers/Diner/DinerLoginController.php
<?php

namespace App\Http\Controllers\Diner;

use App\Http\Requests\Common\LoginRequest;
use App\Http\Services\Diner\DinerLoginService;
use Illuminate\Support\Facades\Auth;
Use URL;

class DinerLoginController extends DinerController
{
    private $dinerLoginObj;

    public function __construct(DinerLoginService $dinerLoginObj)
    {
        $this->dinerLoginObj = $dinerLoginObj;
    }

    public function login()
    {
        if (!Auth::guard('diner')->user()) {
            $this->data['title'] = (object)['name' => 'Login'];
            return view('diner.auth.login', $this->data);
        }
        return redirect()->route('diner.menu.index');
    }

    public function doLogin(LoginRequest $request)
    {
        $credentials = $request->except(['_token', 'remember']);

        $isLogin = $this->dinerLoginObj->login($credentials, $request->remember);

        if ($isLogin) {
            return redirect()->route('diner.menu.index')->with(['success' => 'Logged in successfully']);
        } else {
            return redirect()->back()->with('fail', 'Whoops something wrong');
        }

    }

    public function logout()
    {
        $this->dinerLoginObj->logout();
        return redirect()->route('landing.login');
    }
}

resources/views/diner/order/index.blade.php
@extends('diner.layouts.master')

@section('styling')
    <link rel="stylesheet" type="text/css" media="screen" href="{{asset('assets/css/select2.min.css')}}">
@stop
@section('content')

    <div class="search-field">
        {{Form::open(array('url'=>route('diner.order.index',['venue_id'=>$venue_id]) ,'method'=>'GET','class'=>"form-inline md-form form-sm mt-0"))}}
        <input class="form-control form-control-sm ml-3 w-75" value="{{\Request::Input('keyword')}}" type="text"
               name="keyword" placeholder="Search Ticket ID"
               aria-label="Search">
        <i class="fas fa-search" aria-hidden="true"></i>
        {{Form::close()}}
    </div>

    <div class="sort-option float-right">
        <ul id="keep-on">
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">FILTER
                    <b class="caret"></b></a>
                <div class="dropdown-menu">
                    <h3>Filter</h3>


                    <div class="form-group">
                        <label>Order Date</label>
                        <div class="row">
                            <div class="col-6">
                                <input type="date" placeholder="From"
                                       value="{{\Request::Input('order_date_from') ? date('Y-m-d',strtotime(\Request::Input('order_date_from'))) :'' }}"
                                       id="order_date_from" class="form-control">
                            </div>
                            <div class="col-6">
                                <input type="date" placeholder="To"
                                       value="{{\Request::Input('order_date_to') ? date('Y-m-d',strtotime(\Request::Input('order_date_to'))) :'' }}"
                                       id="order_date_to" class="form-control">
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label>Status</label>

                        <div class="d-flex justify-content-between">
                            <div class="text-muted">
                                Close
                            </div>
                            <div>
                                <label class="switch">
                                    <input type="checkbox" id="status"
                                           {{\Request::Input('status') && \Request::Input('status')==1 ?'checked':''}} value="close"
                                           class="primary">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                            <div class="text-muted">
                                Open
                            </div>
                        </div>

                    </div>
                    <div class="form-group d-flex justify-content-between mt-3">
                        <button class="dark-btn h-40" id="filter_btn">FILTER</button>
                        <button class="plain-btn h-40 dismissDD">CANCEL</button>
                    </div>
                </div>
            </li>

        </ul>
    </div>


    <div class="table-component table-responsive">
        <table class="table table-hover table-borderless">
            <thead>
            <tr>
                <th>Status</th>
                <th>Ticket ID</th>
                <th>Table Number</th>
                <th>Update Time</th>
                <th>Sent Time</th>
            </tr>
            </thead>
            <tbody>
            @if($orders)
                @foreach($orders as $order)
                    <tr class="viewCustomer" data-href="{{URL::to('diner/order/'.$order->id.'?venue_id='.$venue_id)}}">
                        <td>{{$order->status}}</td>
                        <td>{{$order->id}}</td>
                        <td>{{$order->table_number}}</td>
                        <td>{{$order->updated_at}}</td>
                        <td>{{$order->created_at}}</td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>

        <nav>
            <div class="float-right pagination-filter">
                <div>
                    <label>Showing</label>
                    <select class="form-control">
                        <option>10 items per page</option>
                    </select>
                </div>
            </div>
            {{$orders->links()}}
            {{--<ul class="pagination justify-content-center">--}}
            {{--<li class="page-item disabled">--}}
            {{--<a class="page-link" href="#" tabindex="-1"><i--}}
            {{--class="fas fa-angle-left"></i></a>--}}
            {{--</li>--}}
            {{--<li class="page-item active"><a class="page-link" href="#">1</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
            {{--<li class="page-item">--}}
            {{--<a class="page-link" href="#"><i class="fas fa-angle-right"></i></a>--}}
            {{--</li>--}}
            {{--</ul>--}}

        </nav>
    </div>
@stop

@section('scripts')
    <script src="{{asset('assets/js/select2.full.min.js')}}"></script>

    <script>

        $('#keep-on .dropdown-menu').on({
            "click": function (e) {
                e.stopPropagation();
            }
        });

        $(".dismissDD").on('click', function () {
            $(".dropdown-toggle").dropdown("hide");
        });

        $(document).ready(function () {
            $("#country_id").trigger("change");
        });

        $('#country_id').change(function () {

            id = $(this).val()
            if (id) {
                $.ajax({
                    method: "GET",
                    url: "{{URL::to('admin/ajax/cities')}}",
                    data: {id: id}
                })
                    .done(function (data) {
                        $('city_id').append(data)
                    });
            }
        });

        $(".select2").select2();


        $(".viewCustomer").click(function () {
            window.location = $(this).data("href");
        });

        $('#filter_btn').click(function () {
            var status = $('#status').is(":checked") ? 'open' : 'close';
            var order_date_from = $('#order_date_from').val()
            var order_date_to = $('#order_date_to').val();

            url = updateQueryStringParameter(window.location.href, 'status', status);
            url = updateQueryStringParameter(url, 'order_date_from', order_date_from);
            url = updateQueryStringParameter(url, 'order_date_to', order_date_to);
            window.location = url;
        });


        $('#sort_btn').click(function () {
            var sort_by = $('.sorting-buttons.selected').attr('id');
            if (sort_by) {
                url = updateQueryStringParameter(window.location.href, 'sort_by', sort_by);
                window.location = url;
            }
        });

        function updateQueryStringParameter(url, key, value) {
            if (!url) {
                uri = window.location.href;
            } else {
                uri = url;
            }

            var re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
            var separator = uri.indexOf('?') !== -1 ? "&" : "?";
            if (uri.match(re)) {
                return uri.replace(re, '$1' + key + "=" + value + '$2');
            } else {
                return uri + separator + key + "=" + value;
            }
        }

        $('.sorting-buttons').click(function () {
            $('.sorting-buttons').each(function () {
                $(this).removeClass('selected');
            });

            $(this).addClass('selected');
        })
    </script>


@stop

resources/views/diner/order/show.blade.php
@extends('diner.layouts.master')

@section('styling')
    <link rel="stylesheet" type="text/css" media="screen" href="{{asset('assets/css/select2.min.css')}}">
@stop
@section('content')

    <div class="sort-option float-left">
      <p >Last Update: {{$current_order->updated_at}}</p>
      <p >Created: {{$current_order->created_at}}</p>
      <p >Waiter: {{$waiter->name}}</p>
    </div>
    <div class="sort-option float-right">
      <p >Service Charge: {{$current_order->service_charge}}</p>
      <p >Tax: {{$current_order->tax}}</p>
      <p >Tip: {{$current_order->tip}}</p>
      <p >Total Billed: {{$current_order->total_cost}}</p>
    </div>


    <div class="table-component table-responsive">
        <table class="table table-hover table-borderless">
            <thead>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Sent</th>
            </tr>
            </thead>
            <tbody>
                @foreach($current_order->cart->items as $cartItem)
                <tr class="viewCustomer">
                    <td>{{$cartItem->item->name}}</td>
                    <td>{{$cartItem->quantity}}</td>
                    <td>{{$cartItem->item_price * $cartItem->quantity}}</td>
                    <td>{{$cartItem->created_at}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
@stop